webtalk_init -webtalk_dir E:/Desktop/ElevatorControlSystem/ElevatorControlSystem.sim/sim_1/behav/xsim/xsim.dir/DisplayBCD_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep 11 10:56:42 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b956d62c-dd16-41ec-bd9e-a0ac58f4388d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a81ed7cd808548f6b97b8fdc6ef5de07" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A8-8600P Radeon R6, 10 Compute Cores 4C+6G " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1597 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5828_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2850165837 -regid "" -xml E:/Desktop/ElevatorControlSystem/ElevatorControlSystem.sim/sim_1/behav/xsim/xsim.dir/DisplayBCD_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Desktop/ElevatorControlSystem/ElevatorControlSystem.sim/sim_1/behav/xsim/xsim.dir/DisplayBCD_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Desktop/ElevatorControlSystem/ElevatorControlSystem.sim/sim_1/behav/xsim/xsim.dir/DisplayBCD_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
